### PR TITLE
Update for laravel 9

### PR DESCRIPTION
**Pull request by xndbogdan**

### CODE REVIEW

**Comment by imran300** [comment]
Hello, I am having this compatibility issue. Kindly Help please..

Capture

**Comment by schoolbooking-mark** [comment]
I am also having the same problem as @imran300 

I am running the command -  composer require laravel-frontend-presets/tailwindcss --dev

and get the following error :-

Running composer update laravel-frontend-presets/tailwindcss
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
**Your requirements could not be resolved to an installable set of packages.**

  **Problem 1
    - laravel-frontend-presets/tailwindcss[4.3.0, ..., 4.3.1] require laravel/framework ^8.0 -> found laravel/framework[v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.2).
    - Root composer.json requires laravel-frontend-presets/tailwindcss ^4.3 -> satisfiable by laravel-frontend-presets/tailwindcss[4.3.0, 4.3.1].**

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require laravel-frontend-presets/tailwindcss:*" to figure out if any version is installable, or "composer require laravel-frontend-presets/tailwindcss:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.



I have tried to use the  --with-all-dependencies (-W)  but that doesn't work either...

**Comment by carlosolivas** [comment]
Hello,

I'm also having the same issue... is this project still active?

**Comment by xndbogdan** [comment]
I'm thinking of forking the repo if the PR doesn't get pulled in soon.

**Comment by xndbogdan** [comment]
Releasing as separate package here:
https://packagist.org/packages/xndbogdan/tailwindcss
Install it and have fun.

**Comment by elgallouchi** [comment]
Thank you this solved my problem.

`composer require xndbogdan/tailwindcss`

**Pull request closed without merging**
